import '../assets/vendor/jquery/jquery'
import '../assets/vendor/bootstrap/js/bootstrap.bundle'
import '../assets/vendor/jquery-easing/jquery.easing'
import '../assets/js/sb-admin-2'
// import 'https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js'